version: '2'

services:
  database:
    image: ${DATABASE_VERSION}
    networks:
      - backend
    container_name: ${DATABASE_CONTAINER_NAME}
    volumes:
      - mongo-data:/data/db
      - ./docker/scripts:/scripts
      - ./docker/data:/data

  node_server_1:
    environment:
      - NODE=${NODE_CONTAINER_NAME_1}
    container_name: ${NODE_CONTAINER_NAME_1}
    image: ${NODE_VERSION}
    build:
      context: ./web
      dockerfile: node.dockerfile
    networks:
      - backend
    ports:
      - "81:3000"
    volumes:
      - ./web:/web

  node_server_2:
    environment:
      - NODE=${NODE_CONTAINER_NAME_2}
    container_name: ${NODE_CONTAINER_NAME_2}
    image: ${NODE_VERSION}
    build:
      context: ./web
      dockerfile: node.dockerfile
    networks:
      - backend
    ports:
      - "82:3000"
    volumes:
      - ./web:/web

networks:
  backend:
    driver: bridge

volumes:
  mongo-data: